#!/usr/bin/env bash
set -e

export INSTALL_BASE_URL="${INSTALL_BASE_URL:-https://install.example.com/}"
export OFFICE_INSTALL_TMP_DIR="${OFFICE_INSTALL_TMP_DIR:-/tmp/office_install}"

mkdir -p "$OFFICE_INSTALL_TMP_DIR/tools/translation/assets"
echo "Downloading: ${INSTALL_BASE_URL%/}/install.py"
wget --show-progress --progress=bar:force:noscroll "${INSTALL_BASE_URL%/}/install.py" -O "$OFFICE_INSTALL_TMP_DIR/install.py"
source /etc/profile

if [ "$UID" -ne 0 ]; then
    sudo apt install python3-distro python3-yaml -y
    sudo --preserve-env=INSTALL_BASE_URL,OFFICE_INSTALL_TMP_DIR python3 "$OFFICE_INSTALL_TMP_DIR/install.py"
    sudo rm -rf "$OFFICE_INSTALL_TMP_DIR"
else
    apt install python3-distro python3-yaml -y
    python3 "$OFFICE_INSTALL_TMP_DIR/install.py"
    rm -rf "$OFFICE_INSTALL_TMP_DIR"
fi

# 初始假设默认是 Bash
shell_name='bash'
if shopt -u lastpipe 2> /dev/null; then
    # 当前 shell 是 Bash
    :
else
    # 当前 shell 是 Zsh 或其他 shell
    if test -n "$ZSH_VERSION"; then
        shell_name='zsh'
    else
        # 当前使用的 shell 不是 Bash 或 Zsh
        shell_name=''
    fi
fi

# 根据 shell 名称加载相应的配置文件
if [ "$shell_name" = "bash" ]; then
    if [ -f ~/.bashrc ]; then
        source ~/.bashrc
    fi
elif [ "$shell_name" = "zsh" ]; then
    if [ -f ~/.zshrc ]; then
        source ~/.zshrc
    fi
fi
