# -*- coding: utf-8 -*-
import os
import pwd
import shlex
import time

from .base import BaseTool, CmdTask, PrintUtils


OH_MY_ZSH_REPO = "https://github.com/ohmyzsh/ohmyzsh.git"
AUTOSUGGESTIONS_REPO = "https://github.com/zsh-users/zsh-autosuggestions.git"
SYNTAX_HIGHLIGHTING_REPO = "https://github.com/zsh-users/zsh-syntax-highlighting.git"


class Tool(BaseTool):
    def __init__(self):
        self.name = "Oh My Zsh"
        self.type = BaseTool.TYPE_INSTALL
        self.author = "WingBot"

    def _check_sudo(self):
        sudo_check = CmdTask("sudo -n true", 0).run()
        if sudo_check[0] != 0:
            PrintUtils.print_error("当前会话无法无交互使用 sudo，请在终端中运行安装器并输入 sudo 密码后重试。")
            return False
        return True

    def _target_user(self):
        username = os.environ.get("SUDO_USER") or os.environ.get("LOGNAME") or os.environ.get("USER") or "root"
        if username == "root":
            return "root", "/root"
        try:
            info = pwd.getpwnam(username)
            return username, info.pw_dir
        except KeyError:
            return username, os.path.expanduser("~" + username)

    def _run_as_user(self, command):
        user, home = self._target_user()
        if user == "root":
            return CmdTask(command, 0).run()
        wrapped = "sudo -u {user} HOME={home} {command}".format(
            user=shlex.quote(user),
            home=shlex.quote(home),
            command=command,
        )
        return CmdTask(wrapped, 0).run()

    def _install_dependencies(self):
        packages = [
            "zsh",
            "git",
            "curl",
            "ca-certificates",
            "fonts-powerline",
        ]
        CmdTask("sudo apt update", 0).run()
        result = CmdTask("sudo apt install -y {}".format(" ".join(packages)), 0).run()
        if result[0] != 0:
            PrintUtils.print_error("Oh My Zsh 依赖安装失败，请检查 apt 源和网络连接。")
            return False
        return True

    def _clone_or_update(self, repo, path):
        quoted_path = shlex.quote(path)
        quoted_repo = shlex.quote(repo)
        if os.path.isdir(os.path.join(path, ".git")):
            PrintUtils.print_info("检测到已存在仓库，尝试更新: {}".format(path))
            result = self._run_as_user("git -C {} pull --ff-only".format(quoted_path))
            if result[0] != 0:
                PrintUtils.print_warn("仓库更新失败，继续使用已有内容: {}".format(path))
            return True

        if os.path.exists(path):
            PrintUtils.print_warn("目标目录已存在但不是 git 仓库，跳过克隆: {}".format(path))
            return True

        parent = os.path.dirname(path)
        os.makedirs(parent, exist_ok=True)
        user, _ = self._target_user()
        if user != "root":
            CmdTask("sudo chown -R {}:{} {}".format(shlex.quote(user), shlex.quote(user), shlex.quote(parent)), 0).run()

        result = self._run_as_user("git clone --depth=1 {} {}".format(quoted_repo, quoted_path))
        if result[0] != 0:
            PrintUtils.print_error("克隆失败: {}".format(repo))
            return False
        return True

    def _install_ohmyzsh(self):
        _, home = self._target_user()
        zsh_dir = os.path.join(home, ".oh-my-zsh")
        if not self._clone_or_update(OH_MY_ZSH_REPO, zsh_dir):
            return False

        custom_dir = os.path.join(zsh_dir, "custom")
        plugins_dir = os.path.join(custom_dir, "plugins")
        os.makedirs(plugins_dir, exist_ok=True)
        user, _ = self._target_user()
        if user != "root":
            CmdTask("sudo chown -R {}:{} {}".format(shlex.quote(user), shlex.quote(user), shlex.quote(custom_dir)), 0).run()

        plugins = [
            (AUTOSUGGESTIONS_REPO, os.path.join(plugins_dir, "zsh-autosuggestions")),
            (SYNTAX_HIGHLIGHTING_REPO, os.path.join(plugins_dir, "zsh-syntax-highlighting")),
        ]
        for repo, path in plugins:
            if not self._clone_or_update(repo, path):
                return False
        return True

    def _write_zshrc(self):
        user, home = self._target_user()
        zshrc_path = os.path.join(home, ".zshrc")
        if os.path.exists(zshrc_path):
            backup_path = zshrc_path + ".bak.office-install-" + time.strftime("%Y%m%d%H%M%S")
            os.replace(zshrc_path, backup_path)
            PrintUtils.print_warn("检测到已有 .zshrc，已备份: {}".format(backup_path))

        content = """# Generated by office-install.
export ZSH=\"$HOME/.oh-my-zsh\"
ZSH_THEME=\"robbyrussell\"

HISTFILE=\"$HOME/.zsh_history\"
HISTSIZE=10000
SAVEHIST=10000
setopt append_history
setopt share_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt inc_append_history

plugins=(
  git
  sudo
  history
  history-substring-search
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

export EDITOR=vim
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
"""
        with open(zshrc_path, "w", encoding="utf-8") as f:
            f.write(content)
        if user != "root":
            CmdTask("sudo chown {}:{} {}".format(shlex.quote(user), shlex.quote(user), shlex.quote(zshrc_path)), 0).run()
        PrintUtils.print_success("Oh My Zsh 默认配置已写入: {}".format(zshrc_path))
        return True

    def _ensure_zsh_in_shells(self, zsh_path):
        try:
            with open("/etc/shells", "r", encoding="utf-8") as f:
                shells = [line.strip() for line in f if line.strip()]
        except OSError:
            shells = []

        if zsh_path in shells:
            return True

        result = CmdTask("printf '%s\n' {} | sudo tee -a /etc/shells >/dev/null".format(shlex.quote(zsh_path)), 0).run()
        if result[0] != 0:
            PrintUtils.print_warn("无法写入 /etc/shells，chsh 可能失败: {}".format(zsh_path))
            return False
        return True

    def _set_default_shell(self):
        user, _ = self._target_user()
        zsh_path_result = CmdTask("command -v zsh", 0).run()
        if zsh_path_result[0] != 0 or not zsh_path_result[1]:
            PrintUtils.print_warn("未找到 zsh 可执行文件，跳过默认 shell 设置。")
            return True

        zsh_path = zsh_path_result[1][0].strip()
        if not zsh_path:
            PrintUtils.print_warn("未找到 zsh 可执行文件，跳过默认 shell 设置。")
            return True

        self._ensure_zsh_in_shells(zsh_path)

        if user == "root":
            result = CmdTask("chsh -s {} root".format(shlex.quote(zsh_path)), 0).run()
        else:
            result = CmdTask("sudo chsh -s {} {}".format(shlex.quote(zsh_path), shlex.quote(user)), 0).run()
        if result[0] != 0:
            PrintUtils.print_warn("默认 shell 设置失败，可稍后手动执行: sudo chsh -s {} {}".format(zsh_path, user))
            return True

        try:
            current_shell = pwd.getpwnam(user).pw_shell
        except KeyError:
            current_shell = ""
        if current_shell != zsh_path:
            PrintUtils.print_warn("默认 shell 设置后校验不一致，当前为: {}".format(current_shell or "未知"))
            return True

        PrintUtils.print_success("已将 {} 的默认 shell 设置为: {}".format(user, zsh_path))
        return True

    def run(self):
        if not self._check_sudo():
            return False
        if not self._install_dependencies():
            return False
        if not self._install_ohmyzsh():
            return False
        if not self._write_zshrc():
            return False
        self._set_default_shell()
        PrintUtils.print_success("Oh My Zsh 安装完成。重新登录或执行 zsh 后生效。")
        return True
